services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    image: frontend-image
    build:
      context: ./frontend
      args:
        FRONT_PORT: ${FRONT_PORT}
    networks:
      - fiscolia
    volumes:
      - ./frontend/srcs:/app/src:Z
    env_file:
      - ../.env


# TODO: PASSER NGINX EN SLIM
  proxy:
    container_name: ${PROJECT_NAME}-proxy
    image: proxy-image
    build: ./proxy
    depends_on:
      frontend:
        condition: service_started
      backend-auth:
        condition: service_started
      # backend-upload:
      #   condition: service_started
    ports:
      - ${PROXY_EXPOSED_PORT}:80
    networks:
      - fiscolia
    env_file:
      - ../.env

  backend-auth:
    container_name: ${PROJECT_NAME}-backend-auth
    image: backend-auth-image
    build: 
      context: ./backend-auth-login
      args:
        BACK_AUTH_PORT: ${BACK_AUTH_PORT}
    security_opt:
      - label:disable
    depends_on:
      db-auth:
        condition: service_healthy
    networks:
      - fiscolia
    volumes:
      - ../models:/models:ro
    env_file:
      - ../.env
    secrets:
      - db_auth_pwd

  db-auth:
    container_name: ${PROJECT_NAME}-db-auth
    image: db-auth-image
    volumes:
      - db_auth:/var/lib/postgresql/data:Z
    build:
      context: ./database-auth
      args:
        DB_AUTH_PORT: ${DB_AUTH_PORT}
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p ${DB_AUTH_PORT} -U ${DB_AUTH_USER} -d ${DB_AUTH_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    networks:
      - fiscolia
    env_file:
      - ../.env
    secrets:
      - db_auth_pwd
      - db_root_pwd

  # backend-upload:
  #   container_name: ${PROJECT_NAME}-backend-upload
  #   image: backend-upload-image
  #   build: ./backend-upload
  #   networks:
  #     - fiscolia
  #   env_file:
  #     - ../.env
  #   restart: unless-stopped

  create-profile:
    container_name: ${PROJECT_NAME}-create-profile
    image: create-profile-image
    build:
      context: ../scripts/create_profile
    depends_on:
      backend-auth:
        condition: service_started
    networks:
      - fiscolia
    env_file:
      - ../.env
    profiles:
      - profile

networks:
  fiscolia:
    name: fiscolia-network
    driver: bridge

volumes:
  db_auth:
    driver: local

secrets:
  db_auth_pwd:
    file: ../secrets/db_auth_pwd.txt
  db_root_pwd:
    file: ../secrets/db_root_pwd.txt

