services:
  frontend:
    container_name: ${PROJECT_NAME}-frontend
    image: frontend-image
    build:
      context: ./frontend
      args:
        FRONT_PORT: ${FRONT_PORT}
    networks:
      - fiscolia
    volumes:
      - ./frontend/srcs:/app/src:Z
    env_file:
      - ../.env
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "fiscolia-frontend"
        mode: non-blocking
    depends_on:
      logstash:
        condition: service_healthy


  proxy:
    container_name: ${PROJECT_NAME}-proxy
    image: proxy-image
    build: ./proxy
    ports:
      - 443:443
    networks:
      - fiscolia
    env_file:
      - ../.env
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "fiscolia-proxy"
        mode: non-blocking
    depends_on:
      frontend:
        condition: service_started
      backend-auth:
        condition: service_started
      logstash:
        condition: service_healthy
      backend-chatbot:
        condition: service_started


  backend-chatbot:
    container_name: ${PROJECT_NAME}-backend-chatbot
    image: backend-chatbot-image
    build: 
      context: ./backend-chatbot
      args:
        BACK_CHATBOT_PORT: ${BACK_CHATBOT_PORT}
    depends_on:
      ollama:
        condition: service_started
    networks:
      - fiscolia
    env_file:
      - ../.env

  backend-auth:
    container_name: ${PROJECT_NAME}-backend-auth
    image: backend-auth-image
    build: 
      context: ./backend-auth-login
      args:
        BACK_AUTH_PORT: ${BACK_AUTH_PORT}
    security_opt:
      - label:disable
    depends_on:
      db-auth:
        condition: service_healthy
      #hashi-corp-vault:
      #  condition: service_started

    networks:
      - fiscolia
    volumes:
      - ../models:/models:ro
    env_file:
      - ../.env
    secrets:
      - db_auth_pwd
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "fiscolia-backend-auth"
        mode: non-blocking
    depends_on:
      db-auth:
        condition: service_healthy
      logstash:
        condition: service_healthy

  db-auth:
    container_name: ${PROJECT_NAME}-db-auth
    image: db-auth-image
    volumes:
      - db_auth:/var/lib/postgresql/data:Z
    build:
      context: ./database-auth
      args:
        DB_AUTH_PORT: ${DB_AUTH_PORT}
    security_opt:
      - label:disable
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p ${DB_AUTH_PORT} -U ${DB_AUTH_USER} -d ${DB_AUTH_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    networks:
      - fiscolia
    env_file:
      - ../.env
    secrets:
      - db_auth_pwd
      - db_root_pwd
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "fiscolia-db-auth"
        mode: non-blocking
    depends_on:
      logstash:
        condition: service_healthy

  # backend-upload:
  #   container_name: ${PROJECT_NAME}-backend-upload
  #   image: backend-upload-image
  #   build: ./backend-upload
  #   networks:
  #     - fiscolia
  #   env_file:
  #     - ../.env
  #   restart: unless-stopped
  ollama:
    container_name: ${PROJECT_NAME}-ollama
    image: ollama-image
    build:
      context: ./ollama
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - fiscolia
    env_file:
      - ../.env


  create-profile:
    container_name: ${PROJECT_NAME}-create-profile
    image: create-profile-image
    build:
      context: ../scripts/create_profile
    depends_on:
      backend-auth:
        condition: service_started
    networks:
      - fiscolia
    env_file:
      - ../.env
    profiles:
      - profile-create-profile

  create-user:
    container_name: ${PROJECT_NAME}-create-user
    image: create-user-image
    build:
      context: ../scripts/create_user
    depends_on:
      backend-auth:
        condition: service_started
    networks:
      - fiscolia
    env_file:
      - ../.env
    profiles:
      - profile-create-user

  training:
    container_name: ${PROJECT_NAME}-training
    image: fiscolia-training
    build:
      context: ./training
    depends_on:
      db-auth:
        condition: service_started
    volumes:
      - ../models:/app/models:Z
    networks:
      - fiscolia
    env_file:
      - ../.env
    profiles:
      - training
    secrets:
      - db_auth_pwd

  logstash:
    container_name: ${PROJECT_NAME}-logstash
    image: logstash-image
    build: ./logs-logstash
    networks:
      - fiscolia
    env_file:
      - ../.env
    ports:
      - "127.0.0.1:12201:12201/udp"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9600/"]
      timeout: 5s
      retries: 10
      start_period: 40s
      interval: 5s
    volumes:
      - ../logs_archives:/usr/share/logstash/backups:Z
    depends_on:
      elasticsearch:
        condition: service_healthy
  
  elasticsearch:
    container_name: ${PROJECT_NAME}-elasticsearch
    image: elasticsearch-image
    build: ./logs-elasticsearch
    expose:
      - 9200
    networks:
      - fiscolia
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:Z

  kibana:
    container_name: ${PROJECT_NAME}-kibana
    image: kibana-image
    build: ./logs-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://fiscolia-elasticsearch:9200
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    volumes:
      - ./logs-kibana/conf/export.ndjson:/tmp/dashboards.ndjson:ro,Z
    expose:
      - 5601
    networks:
      - fiscolia
    logging:
      driver: gelf
      options:
        gelf-address: "udp://127.0.0.1:12201"
        tag: "fiscolia-kibana"
        mode: non-blocking
    depends_on:
      logstash:
        condition: service_healthy 
    restart: always


  hashi-corp-vault:
    container_name: ${PROJECT_NAME}-vault
    image: vault-image
    build:
      context: ./hashi-corp-vault
      args:
        VAULT_PORT: ${VAULT_PORT}
        VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
        VAULT_DEV_LISTEN_ADDRESS: ${VAULT_DEV_LISTEN_ADDRESS}
        VAULT_ADDR: ${VAULT_ADDR}
    ports:
      - ${VAULT_PORT}:${VAULT_PORT}
    cap_add:
      - IPC_LOCK
    env_file:
      - ../.env
    networks:
      - fiscolia


networks:
  fiscolia:
    name: fiscolia-network
    driver: bridge

volumes:
  db_auth:
    driver: local
  ollama_models:
    driver: local
  elasticsearch_data:
    driver: local

secrets:
  db_auth_pwd:
    file: ../secrets/db_auth_pwd.txt
  db_root_pwd:
    file: ../secrets/db_root_pwd.txt