FROM docker.io/library/elasticsearch:9.2.8

COPY ./conf/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml

# TODO: ELASTICSEARCH UTILISE HTTPS PAR DEFAUT A VOIR SI SUPPR OU NON
CMD ["elasticsearch"]