input {
  gelf {
    port => 12201
    host => "0.0.0.0"
  }
}

filter {
  if [tag] =~ "fiscolia-kibana" and [message] !~ "INFO" {
    drop { }
  }
  if [tag] =~ "fiscolia-backend-auth" {
    grok {
      match => { "message" => "%{IP:client_ip}:%{POSINT:client_port}%{SPACE}-%{SPACE}\"(%{WORD:method})?%{SPACE}(%{URIPATH:request_path})?%{SPACE}HTTP/%{NUMBER:http_version}\"%{SPACE}%{NUMBER:response_code}%{SPACE}%{WORD:response_message}" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://fiscolia-elasticsearch:9200"]
    index => "fiscolia-logs-%{+YYYY.MM.dd}"
  }
  file {
    path => "/usr/share/logstash/backups/archive-%{+YYYY-MM-dd}.log.gz"
    codec => line { format => "%{message}" }
    gzip => true
  }
  stdout { 
    codec => rubydebug 
  }
}
