name: Fiscolia CI Checker

on: [push]

jobs:
  run-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files for debugging
        run : |
              echo "checking out code"
              ls -la
              echo "------------------------------"
              tree

      - name : Create env variables for docker environment
        env:
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run : env | grep PROJECT_NAME

      - name: Create .env file and secrets
        run: |
          mkdir -p secrets
          echo "${{ secrets.DB_AUTH_PWD }}" > secrets/db_auth_pwd.txt
          echo "${{ secrets.DB_ROOT_PWD }}" > secrets/db_root_pwd.txt
          echo "PROJECT_NAME=${{ vars.PROJECT_NAME }}" > .env
          echo "PROXY_EXPOSED_PORT=${{ vars.PROXY_EXPOSED_PORT }}" >> .env 
          echo "DB_AUTH_USER=${{ vars.DB_AUTH_USER }}" >> .env
          echo "DB_AUTH_SECRETS=${{ vars.DB_AUTH_SECRETS }}" >> .env
          echo "DB_AUTH_PORT=${{ vars.DB_AUTH_PORT }}" >> .env
          echo "DB_AUTH_NAME=${{ vars.DB_AUTH_NAME }}" >> .env
          echo "BACK_AUTH_PORT=${{ vars.BACK_AUTH_PORT }}" >> .env
          echo "BACK_UPLOAD_PORT=${{ vars.BACK_UPLOAD_PORT }}" >> .env
          echo "FRONT_PORT=${{ vars.FRONT_PORT }}" >> .env
          echo "POSTGRES_PASSWORD_FILE=${{ vars.POSTGRES_PASSWORD_FILE }}" >> .env
          echo "BACK_CHATBOT_PORT=${{ vars.BACK_CHATBOT_PORT }}" >> .env
          echo "OLLAMA_MODELS_PATH=${{ vars.OLLAMA_MODELS_PATH }}" >> .env
          echo "VERIFICATION .env FILE CONTENT"
          cat .env
          echo "VERIFICATION secrets FILE CONTENT"
          cat secrets/db_auth_pwd.txt
          cat secrets/db_root_pwd.txt

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Verification Python setup
        run : python --version

      - name : Build and start services
        run: make github-actions

      - name: Discord Notification on Failure
        if: failure()
        uses: actions/github-script@v6
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          REPO_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        with:
          script: |
            const payload = {
              username: "Fiscolia Monitor Failure",
              embeds: [{
                title: "❌ Build Failed",
                color: 65280,
                description: `**Branche :** \`${context.ref.replace('refs/heads/', '')}\`\n**Message :** ${context.payload.head_commit.message}\n**Auteur :** ${context.actor}\n\n[👉 Voir les détails](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
                footer: { text: "Fiscolia Launch Failure" }
              }]
            };   

            await fetch(process.env.DISCORD_WEBHOOK, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(payload)
            });

      - name: Discord Notification on Success
        if: success()
        uses: actions/github-script@v6
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          COMMIT_MSG: ${{ github.event.head_commit.message }}
          REPO_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        with:
          script: |
            const payload = {
              username: "Fiscolia Monitor Success",
              embeds: [{
                title: "✅ Build Success",
                color: 65280,
                description: `**Branche :** \`${context.ref.replace('refs/heads/', '')}\`\n**Message :** ${context.payload.head_commit.message}\n**Auteur :** ${context.actor}\n\n[👉 Voir les détails](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId})`,
                footer: { text: "Fiscolia Infrastructure is UP" }
              }]
            };   

            await fetch(process.env.DISCORD_WEBHOOK, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify(payload)
            });

      - name: Stop services and clean up
        if: always()
        run: make fclean